# Generated by Django 5.0.1 on 2024-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gmw",
            old_name="delivery_location",
            new_name="ground_level_position",
        ),
        migrations.AddField(
            model_name="gmw",
            name="ground_level_positiong_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmw",
            name="local_vertical_reference_point",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmw",
            name="offset",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmw",
            name="vertical_datum",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
