# Generated by Django 5.0.1 on 2024-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0003_remove_gmw_delivered_vertical_postition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gmw",
            name="deliverd_location",
        ),
        migrations.AddField(
            model_name="gmw",
            name="delivered_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
