# Generated by Django 5.0.1 on 2024-02-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0004_remove_gmw_deliverd_location_gmw_delivered_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gmw",
            old_name="ground_level_positiong_method",
            new_name="ground_level_positioning_method",
        ),
        migrations.AddField(
            model_name="monitoringtube",
            name="sediment_sump_present",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
