# Generated by Django 5.0.1 on 2024-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0009_alter_gmw_well_stability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmw",
            name="construction_standard",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="delivered_location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="delivery_accountable_party",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="delivery_context",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="ground_level_position",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="ground_level_positioning_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="ground_level_stable",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="initial_function",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="local_vertical_reference_point",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="nitg_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="object_registration_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="offset",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="owner",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="quality_regime",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="registration_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="removed",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="standardized_location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="vertical_datum",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="well_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmw",
            name="well_head_protector",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="artesian_well_cap_present",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="glue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="number_of_geo_ohm_cables",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="plain_tube_part_length",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="screen_bottom_position",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="screen_length",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="screen_top_position",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="sediment_sump_present",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="sock_material",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_in_use",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_material",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_packing_material",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_part_inserted",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_top_position",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_top_positioning_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="tube_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="variable_diameter",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
