# Generated by Django 5.0.4 on 2024-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0011_rename_created_at_gmw_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringtube",
            name="geo_ohm_cables",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Geoohm Cables"
            ),
        ),
    ]
