# Generated by Django 5.0.4 on 2024-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0012_monitoringtube_geo_ohm_cables"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringtube",
            name="sediment_sump_length",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
