# Generated by Django 5.0.4 on 2024-11-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0014_monitoringtube_screen_protection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmw",
            name="horizontal_positioning_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmw",
            name="well_construction_date",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
