# Generated by Django 5.0.4 on 2024-12-05 18:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_alter_uploadtask_registration_type"),
        ("gmw", "0015_gmw_horizontal_positioning_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("event_name", models.CharField(max_length=40)),
                ("event_date", models.DateField()),
                ("metadata", models.JSONField(default=dict, verbose_name="Metadata")),
                (
                    "sourcedocument_data",
                    models.JSONField(default=dict, verbose_name="Sourcedocument data"),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "gmw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gmw.gmw"
                    ),
                ),
            ],
        ),
    ]
