# Generated by Django 5.0.4 on 2025-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0016_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="monitoringtube",
            options={"verbose_name_plural": "Monitoring Tubes"},
        ),
        migrations.AddField(
            model_name="gmw",
            name="nr_of_intermediate_events",
            field=models.IntegerField(null=True),
        ),
    ]
