# Generated by Django 5.0.4 on 2025-01-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0017_alter_event_options_alter_monitoringtube_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gmw",
            name="nr_of_intermediate_events",
        ),
        migrations.AlterField(
            model_name="event",
            name="gmw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="gmw.gmw",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="gmw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tubes",
                to="gmw.gmw",
            ),
        ),
    ]
