# Generated by Django 5.0.14 on 2025-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0019_alter_gmw_nitg_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmw",
            name="intern_id",
            field=models.CharField(
                blank=True,
                help_text="Alleen beschikbaar voor de eigenaar van de put.",
                max_length=50,
                null=True,
            ),
        ),
    ]
