# Generated by Django 5.0.14 on 2025-07-04 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0020_gmw_intern_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gmw",
            old_name="intern_id",
            new_name="internal_id",
        ),
    ]
