# Generated by Django 5.2.7 on 2025-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmw", "0021_rename_intern_id_gmw_internal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmw",
            name="internal_id",
            field=models.CharField(
                blank=True,
                help_text="Alleen beschikbaar voor de eigenaar van de put.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monitoringtube",
            name="geo_ohm_cables",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Geoohm Cables"
            ),
        ),
    ]
