# Generated by Django 5.2.7 on 2026-03-26 18:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0060_alter_uploadtask_registration_type"),
        ("gmw", "0022_alter_gmw_internal_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GUF",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "internal_id",
                    models.CharField(
                        blank=True,
                        help_text="Alleen beschikbaar voor de eigenaar van de put.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("bro_id", models.CharField(max_length=18)),
                ("linked_gmns", models.JSONField(default=list, verbose_name="Gmns")),
                (
                    "delivery_accountable_party",
                    models.CharField(max_length=8, null=True),
                ),
                ("quality_regime", models.CharField(max_length=100, null=True)),
                ("gmw_bro_id", models.CharField(max_length=100, null=True)),
                ("tube_number", models.CharField(max_length=100, null=True)),
                ("research_first_date", models.DateField(blank=True, null=True)),
                ("research_last_date", models.DateField(blank=True, null=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "monitoring_tube",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ground_water_usage_facilities",
                        to="gmw.monitoringtube",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GUF's",
            },
        ),
    ]
