# Generated by Django 5.2.7 on 2026-03-27 10:24

import uuid

import django.db.models.deletion
from django.db import migrations, models

import guf.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_alter_uploadtask_registration_type"),
        ("guf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guf",
            name="gmw_bro_id",
        ),
        migrations.RemoveField(
            model_name="guf",
            name="linked_gmns",
        ),
        migrations.RemoveField(
            model_name="guf",
            name="monitoring_tube",
        ),
        migrations.RemoveField(
            model_name="guf",
            name="research_first_date",
        ),
        migrations.RemoveField(
            model_name="guf",
            name="research_last_date",
        ),
        migrations.RemoveField(
            model_name="guf",
            name="tube_number",
        ),
        migrations.AddField(
            model_name="guf",
            name="delivery_context",
            field=models.CharField(
                blank=True,
                choices=[("waterwet", "Waterwet"), ("omgevingswet", "Omgevingswet")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="end_time",
            field=models.DateField(
                blank=True, help_text="Format: YYYY-MM-DD, YYYY-MM, or YYYY", null=True
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="human_consumption",
            field=models.CharField(
                blank=True,
                choices=[("ja", "Ja"), ("nee", "Nee"), ("onbekend", "Onbekend")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="identification_licence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guf",
            name="legal_type",
            field=models.CharField(
                blank=True,
                choices=[("melding", "Melding"), ("vergunning", "Vergunning")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="licensed_quantities",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Licensed Quantities"
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="primary_usage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agrarischeDoeleinden", "Agrarische doeleinden"),
                    ("bemaling", "Bemaling"),
                    ("bodembeschermingsgebied", "Bodembeschermingsgebied"),
                    ("bodemenergie", "Bodemenergie"),
                    ("drinkwatervoorziening", "Drinkwatervoorziening"),
                    ("geslotenBodemenergiesysteem", "Gesloten bodemenergiesysteem"),
                    ("grondwatersanering", "Grondwatersanering"),
                    ("industrieleToepassing", "Industriele toepassing"),
                    ("infiltratieOpenbaarWater", "Infiltratie openbaar water"),
                    ("infiltratieRegenwater", "Infiltratie regenwater"),
                    ("klimaatbeheersing", "Klimaatbeheersing"),
                    ("koeling", "Koeling"),
                    ("landbouwkundigeDoeleinden", "Landbouwkundige doeleinden"),
                    ("natteInfrastructuur", "Natte infrastructuur"),
                    ("natuurbeheer", "Natuurbeheer"),
                    ("onbekend", "Onbekend"),
                    ("ontwatering", "Ontwatering"),
                    ("openBodemenergiesysteem", "Open bodemenergiesysteem"),
                    ("proceswater", "Proceswater"),
                    ("proefbronnering", "Proefbronnering"),
                    ("suppletie", "Suppletie"),
                    ("verversing", "Verversing"),
                    ("warmte", "Warmte"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="secondary_usage_types",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[guf.models.is_usage_type_options],
                verbose_name="Secondary Usage Types",
            ),
        ),
        migrations.AddField(
            model_name="guf",
            name="start_time",
            field=models.DateField(
                blank=True, help_text="Format: YYYY-MM-DD, YYYY-MM, or YYYY", null=True
            ),
        ),
        migrations.AlterField(
            model_name="guf",
            name="quality_regime",
            field=models.CharField(
                choices=[("IMBRO", "I m b r o"), ("IMBRO/A", "I m b r o/ a")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DesignInstallation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "design_installation_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "installation_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("infiltratie", "Infiltratie"),
                            ("lozen", "Lozen"),
                            ("onttrekking", "Onttrekking"),
                            ("retourneren", "Retourneren"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "design_installation_pos",
                    models.CharField(
                        blank=True,
                        help_text="Point coordinates as string",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "energy_characteristics",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "licensed_quantities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Licensed Quantities"
                    ),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "guf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="guf.guf",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Design Installations",
            },
        ),
        migrations.CreateModel(
            name="DesignLoop",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "design_loop_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "loop_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("horizontaal", "Horizontaal"),
                            ("korf", "Korf"),
                            ("verticaal", "Verticaal"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Format: YYYY-MM-DD, YYYY-MM, or YYYY",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Format: YYYY-MM-DD, YYYY-MM, or YYYY",
                        null=True,
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        blank=True,
                        help_text="Point or LineString",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "design_loop_pos",
                    models.TextField(
                        blank=True,
                        help_text="Geometry coordinates as string",
                        null=True,
                    ),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loops",
                        to="guf.designinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Design Loops",
            },
        ),
        migrations.CreateModel(
            name="DesignSurfaceInfiltration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "design_surface_infiltration_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "design_surface_infiltration_pos",
                    models.TextField(
                        blank=True, help_text="Polygon coordinates as string", null=True
                    ),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surface_infiltrations",
                        to="guf.designinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Design Surface Infiltrations",
            },
        ),
        migrations.CreateModel(
            name="DesignWell",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "design_well_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "well_functions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[guf.models.is_well_function_options],
                        verbose_name="Well Functions",
                    ),
                ),
                ("height", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "well_pos",
                    models.CharField(
                        blank=True,
                        help_text="Point coordinates as string",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "geometry_publicly_available",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ja", "Ja"),
                            ("nee", "Nee"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "maximum_well_depth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "maximum_well_depth_publicly_available",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ja", "Ja"),
                            ("nee", "Nee"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "maximum_well_capacity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "relative_temperature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("koud", "Koud"),
                            ("warm", "Warm"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "design_screen",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Design Screen"
                    ),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wells",
                        to="guf.designinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Design Wells",
            },
        ),
        migrations.CreateModel(
            name="GUFEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        help_text="Event type: Height, NewLicense, WellFunction, Closure, etc.",
                        max_length=40,
                    ),
                ),
                ("event_date", models.DateField()),
                ("metadata", models.JSONField(default=dict, verbose_name="Metadata")),
                (
                    "sourcedocument_data",
                    models.JSONField(default=dict, verbose_name="Sourcedocument data"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "guf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="guf.guf",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GUF Events",
            },
        ),
    ]
