# Generated by Django 5.2.7 on 2026-03-27 10:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_alter_uploadtask_registration_type"),
        ("guf", "0002_remove_guf_gmw_bro_id_remove_guf_linked_gmns_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designinstallation",
            name="energy_characteristics",
        ),
        migrations.CreateModel(
            name="EnergyCharacteristics",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "energy_cold",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "energy_warm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "maximum_infiltration_temperature_warm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "average_infiltration_temperature_cold",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "average_infiltration_temperature_warm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("power_cold", models.CharField(blank=True, max_length=100, null=True)),
                ("power_warm", models.CharField(blank=True, max_length=100, null=True)),
                ("power", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "average_warm_water",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "average_cold_water",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "maximum_year_quantity_warm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "maximum_year_quantity_cold",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "installation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_characteristics",
                        to="guf.designinstallation",
                    ),
                ),
            ],
        ),
    ]
