# Generated by Django 5.2.7 on 2026-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guf", "0003_remove_designinstallation_energy_characteristics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designinstallation",
            name="installation_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("geslotenBodemenergiesysteem", "Gesloten bodemenergiesysteem"),
                    ("onttrekkingEnRetournering", "Onttrekking en retournering"),
                    ("onttrekking", "Onttrekking"),
                    ("infiltratie", "Infiltratie"),
                    ("infiltratieEnOnttrekking", "Infiltratie en onttrekking"),
                    ("openBodemenergiesysteem", "Open bodemenergiesysteem"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guf",
            name="legal_type",
            field=models.CharField(
                blank=True,
                choices=[("melding", "Melding"), ("beschikking", "Beschikking")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guf",
            name="primary_usage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agrarischeDoeleinden", "Agrarische doeleinden"),
                    ("bemaling", "Bemaling"),
                    ("brandblusvoorziening", "Brandblusvoorziening"),
                    ("geslotenBodemenergiesysteem", "Gesloten bodemenergiesysteem"),
                    ("grondwatersanering", "Grondwatersanering"),
                    ("industrieleToepassing", "Industriele toepassing"),
                    ("openBodemenergiesysteem", "Open bodemenergiesysteem"),
                    ("openbareDrinkwatervoorziening", "Openbare drinkwatervoorziening"),
                    ("overigeDoeleinden", "Overige doeleinden"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
