# Generated by Django 5.2.7 on 2026-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guf", "0004_alter_designinstallation_installation_function_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designwell",
            name="geometry_publicly_available",
            field=models.CharField(
                blank=True,
                choices=[("ja", "Ja"), ("nee", "Nee")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="designwell",
            name="maximum_well_depth_publicly_available",
            field=models.CharField(
                blank=True,
                choices=[("ja", "Ja"), ("nee", "Nee")],
                max_length=100,
                null=True,
            ),
        ),
    ]
