# Generated by Django 5.2.7 on 2026-03-26 20:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0060_alter_uploadtask_registration_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPD",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "internal_id",
                    models.CharField(
                        blank=True,
                        help_text="Alleen beschikbaar voor de eigenaar van de put.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("bro_id", models.CharField(max_length=18)),
                (
                    "delivery_accountable_party",
                    models.CharField(max_length=8, null=True),
                ),
                ("quality_regime", models.CharField(max_length=100, null=True)),
                ("start_time", models.DateField(blank=True, null=True)),
                ("end_time", models.DateField(blank=True, null=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GPD's",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("report_id", models.CharField(max_length=100)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("berekening", "Berekening"),
                            ("watermeter", "Watermeter"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=100,
                    ),
                ),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
                ("groundwater_usage_facility_bro_id", models.CharField(max_length=50)),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "gpd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="gpd.gpd",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolumeSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "water_in_out",
                    models.CharField(
                        choices=[
                            ("ingebracht", "Ingebracht"),
                            ("onttrokken", "Onttrokken"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        choices=[
                            ("warm", "Warm"),
                            ("koud", "Koud"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=25,
                    ),
                ),
                ("volume", models.FloatField()),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_series",
                        to="gpd.report",
                    ),
                ),
            ],
        ),
    ]
