# Generated by Django 5.2.7 on 2026-03-26 20:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpd", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volumeseries",
            name="id",
        ),
        migrations.AddField(
            model_name="volumeseries",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
