global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

scrape_configs:
  - job_name: "django_app"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]
