# Generated by Django 5.0.1 on 2024-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="organization",
            new_name="organisation",
        ),
        migrations.AlterField(
            model_name="importtask",
            name="log",
            field=models.TextField(blank=True),
        ),
    ]
