# Generated by Django 5.0.1 on 2024-02-05 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_importtask_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importtask",
            old_name="bro_object",
            new_name="bro_object_type",
        ),
    ]
