# Generated by Django 5.0.1 on 2024-02-05 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_bro_object_importtask_bro_object_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importtask",
            old_name="bro_object_type",
            new_name="bro_domain",
        ),
    ]
