# Generated by Django 5.0.1 on 2024-02-14 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_userprofile_created_at_userprofile_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadTask",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "bro_domain",
                    models.CharField(
                        choices=[
                            ("GMN", "GMN"),
                            ("GMW", "GMW"),
                            ("GLD", "GLD"),
                            ("FRD", "FRD"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[("GMN_StartRegistration", "GMN_StartRegistration")],
                        max_length=235,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("register", "register"),
                            ("replace", "replace"),
                            ("move", "move"),
                            ("insert", "insert"),
                            ("delete", "delete"),
                        ],
                        max_length=235,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=500, null=True)),
                ("log", models.TextField(blank=True)),
            ],
        ),
    ]
