# Generated by Django 5.0.1 on 2024-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_uploadtask_sourcedocument_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadtask",
            name="sourcedocument_data",
            field=models.JSONField(default=dict, verbose_name="Sourcedocument data"),
        ),
    ]
