# Generated by Django 5.0.1 on 2024-02-15 10:06

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_uploadtask_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bro_user_password",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bro_user_token",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
    ]
