# Generated by Django 5.0.1 on 2024-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_userprofile_project_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadtask",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("registration", "registration"),
                    ("replace", "replace"),
                    ("move", "move"),
                    ("insert", "insert"),
                    ("delete", "delete"),
                ],
                max_length=235,
            ),
        ),
    ]
