# Generated by Django 5.0.1 on 2024-02-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_uploadtask_request_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importtask",
            name="organisation",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="project_number",
        ),
        migrations.AddField(
            model_name="importtask",
            name="data_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
        ),
        migrations.AddField(
            model_name="importtask",
            name="kvk_number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="uploadtask",
            name="data_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.organisation",
            ),
        ),
        migrations.AddField(
            model_name="uploadtask",
            name="kvk_number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="uploadtask",
            name="project_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_project_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
        ),
    ]
