# Generated by Django 5.0.1 on 2024-02-21 13:23

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_importtask_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bro_user_password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bro_user_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
