# Generated by Django 5.0.1 on 2024-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_userprofile_first_name_userprofile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
