# Generated by Django 5.0.1 on 2024-02-23 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importtask",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="importtask",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="importtask",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importtask",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
