# Generated by Django 5.0.1 on 2024-03-14 09:55

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_remove_importtask_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bro_user_password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bro_user_token",
        ),
        migrations.AddField(
            model_name="organisation",
            name="bro_user_password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bro_user_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
