# Generated by Django 5.0.1 on 2024-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_remove_userprofile_default_project_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadtask",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("GMN_StartRegistration", "GMN_StartRegistration"),
                    ("GMN_MeasuringPoint", "GMN_MeasuringPoint"),
                    ("GMN_MeasuringPointEndDate", "GMN_MeasuringPointEndDate"),
                    ("GMN_TubeReference", "GMN_TubeReference"),
                    ("GMN_Closure", "GMN_Closure"),
                ],
                max_length=235,
            ),
        ),
    ]
