# Generated by Django 5.0.1 on 2024-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_alter_importtask_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadtask",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
