# Generated by Django 5.0.1 on 2024-04-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_uploadtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
