# Generated by Django 5.0.4 on 2024-04-25 10:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_uploadtask_bro_delivery_url_alter_importtask_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importtask",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                ],
                default=None,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="importtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("UNFINISHED", "Unfinished"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                ],
                default=None,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("GMN_StartRegistration", "GMN_StartRegistration"),
                    ("GMN_MeasuringPoint", "GMN_MeasuringPoint"),
                    ("GMN_MeasuringPointEndDate", "GMN_MeasuringPointEndDate"),
                    ("GMN_TubeReference", "GMN_TubeReference"),
                    ("GMN_Closure", "GMN_Closure"),
                    ("GMW_Construction", "GMW_Construction"),
                    ("GAR", "GAR"),
                ],
                max_length=235,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("UNFINISHED", "Unfinished"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BulkUpload",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "bro_domain",
                    models.CharField(
                        choices=[
                            ("GMN", "GMN"),
                            ("GMW", "GMW"),
                            ("GLD", "GLD"),
                            ("FRD", "FRD"),
                            ("GAR", "GAR"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "bulk_upload_type",
                    models.CharField(
                        choices=[("GAR", "GAR")],
                        default=None,
                        help_text="Determines which process/task to start.",
                        max_length=3,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional json field to add extra data that is not provided within the files, but is required in the processing of the files.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("UNFINISHED", "Unfinished"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("log", models.TextField(blank=True)),
                ("progress", models.FloatField(blank=True, null=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.organisation",
                    ),
                ),
            ],
        ),
    ]
