# Generated by Django 5.0.4 on 2024-04-26 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_alter_importtask_bro_domain_alter_importtask_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkupload",
            name="bro_domain",
        ),
    ]
