# Generated by Django 5.0.4 on 2024-04-26 11:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_remove_bulkupload_bro_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="bulk_uploads/")),
                (
                    "bulk_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.bulkupload"
                    ),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.organisation",
                    ),
                ),
            ],
        ),
    ]
