# Generated by Django 5.0.4 on 2024-04-26 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_bulkuploadfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BulkUploadFile",
            new_name="UploadFile",
        ),
    ]
