# Generated by Django 5.0.4 on 2024-04-30 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_rename_bulkuploadfile_uploadfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="project_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(
                upload_to="bulk_uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xls", "xlsx"]
                    )
                ],
            ),
        ),
    ]
