# Generated by Django 5.0.4 on 2024-05-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_bulkupload_project_number_alter_uploadfile_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        help_text="A space-separated list of {endpoint|*}:{read|readwrite}."
                    ),
                ),
                (
                    "is_password",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this key was migrated from a former password.",
                    ),
                ),
                (
                    "last_used",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Last time the API key was used.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal API Key",
                "verbose_name_plural": "Personal API Keys",
            },
        ),
        migrations.AddConstraint(
            model_name="personalapikey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_password", True)),
                fields=("user",),
                name="unique_password_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalapikey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope__contains", "ftp:readwrite")),
                fields=("user",),
                name="unique_ftp_scope_user",
            ),
        ),
    ]
