# Generated by Django 5.0.4 on 2024-05-01 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_personalapikey_personalapikey_unique_password_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalapikey",
            name="scope",
        ),
    ]
