# Generated by Django 5.0.4 on 2024-05-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_remove_personalapikey_unique_ftp_scope_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="personalapikey",
            name="unique_ftp_scope_user",
        ),
        migrations.AlterField(
            model_name="personalapikey",
            name="scope",
            field=models.TextField(
                default="*:readwrite",
                help_text="A space-separated list of {endpoint|*}:{read|readwrite}.",
            ),
        ),
    ]
