# Generated by Django 5.0.4 on 2024-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_remove_personalapikey_unique_ftp_scope_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkupload",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="Optional json field to add extra data that is not provided within the files, but is required in the processing of the files.",
                verbose_name="Metadata",
            ),
        ),
    ]
