# Generated by Django 5.0.4 on 2024-05-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_alter_bulkupload_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="bulk_upload",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.bulkupload",
            ),
        ),
    ]
