# Generated by Django 5.0.4 on 2024-08-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_inviteuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteuser",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
        ),
    ]
