# Generated by Django 5.0.4 on 2024-08-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_alter_inviteuser_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="inviteuser",
            name="nens_auth_client_invitation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Do not fill in this one.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nens_auth_client.invitation",
            ),
        ),
    ]
