# Generated by Django 5.0.4 on 2024-08-08 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_alter_inviteuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inviteuser",
            name="nens_auth_client_invitation",
        ),
    ]
