# Generated by Django 5.0.4 on 2025-02-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.uploadfile",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="bulk_upload_type",
            field=models.CharField(
                choices=[("GAR", "GAR"), ("GLD", "GLD"), ("GMN", "GMN")],
                default=None,
                help_text="Determines which process/task to start.",
                max_length=3,
            ),
        ),
    ]
