# Generated by Django 5.0.4 on 2025-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_bulkupload_file_alter_bulkupload_bulk_upload_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("registration", "registration"),
                    ("replace", "replace"),
                    ("move", "move"),
                    ("insert", "insert"),
                    ("delete", "delete"),
                ],
                default="registration",
                max_length=235,
            ),
        ),
    ]
