# Generated by Django 5.0.14 on 2025-06-18 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_bulkupload_request_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkupload",
            name="file",
        ),
    ]
