# Generated by Django 5.2.7 on 2025-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_alter_uploadtask_registration_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
