# Generated by Django 5.2.7 on 2026-01-23 09:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_organisation_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroDomain",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "bro_domain",
                    models.CharField(
                        choices=[
                            ("GMN", "GMN"),
                            ("GMW", "GMW"),
                            ("GLD", "GLD"),
                            ("FRD", "FRD"),
                            ("GAR", "GAR"),
                            ("CPT", "CPT"),
                            ("BHR-GT", "BHR-GT"),
                            ("GUF", "GUF"),
                        ],
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BRO Domain",
                "verbose_name_plural": "BRO Domains",
            },
        ),
        migrations.AddField(
            model_name="organisation",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importtask",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                    ("CPT", "CPT"),
                    ("BHR-GT", "BHR-GT"),
                    ("GUF", "GUF"),
                ],
                default=None,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                    ("CPT", "CPT"),
                    ("BHR-GT", "BHR-GT"),
                    ("GUF", "GUF"),
                ],
                default=None,
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bro_domains",
            field=models.ManyToManyField(blank=True, to="api.brodomain"),
        ),
    ]
