# Generated by Django 5.2.7 on 2026-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_brodomain_organisation_renewal_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brodomain",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                    ("CPT", "CPT"),
                    ("BHR", "BHR"),
                    ("GUF", "GUF"),
                    ("GPD", "GPD"),
                ],
                max_length=8,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="importtask",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                    ("CPT", "CPT"),
                    ("BHR", "BHR"),
                    ("GUF", "GUF"),
                    ("GPD", "GPD"),
                ],
                default=None,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="bro_domain",
            field=models.CharField(
                choices=[
                    ("GMN", "GMN"),
                    ("GMW", "GMW"),
                    ("GLD", "GLD"),
                    ("FRD", "FRD"),
                    ("GAR", "GAR"),
                    ("CPT", "CPT"),
                    ("BHR", "BHR"),
                    ("GUF", "GUF"),
                    ("GPD", "GPD"),
                ],
                default=None,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("GMN_StartRegistration", "GMN_StartRegistration"),
                    ("GMN_MeasuringPoint", "GMN_MeasuringPoint"),
                    ("GMN_MeasuringPointEndDate", "GMN_MeasuringPointEndDate"),
                    ("GMN_TubeReference", "GMN_TubeReference"),
                    ("GMN_Closure", "GMN_Closure"),
                    ("GMW_Construction", "GMW_Construction"),
                    ("GMW_ElectrodeStatus", "GMW_ElectrodeStatus"),
                    ("GMW_GroundLevel", "GMW_GroundLevel"),
                    ("GMW_GroundLevelMeasuring", "GMW_GroundLevelMeasuring"),
                    ("GMW_Insertion", "GMW_Insertion"),
                    ("GMW_Lengthening", "GMW_Lengthening"),
                    ("GMW_Shortening", "GMW_Shortening"),
                    ("GMW_Positions", "GMW_Positions"),
                    ("GMW_PositionsMeasuring", "GMW_PositionsMeasuring"),
                    ("GMW_Shift", "GMW_Shift"),
                    ("GMW_Maintainer", "GMW_Maintainer"),
                    ("GMW_Owner", "GMW_Owner"),
                    ("GMW_Removal", "GMW_Removal"),
                    (
                        "GMW_SubsequentAdditionalSurvey",
                        "GMW_SubsequentAdditionalSurvey",
                    ),
                    ("GMW_TubeStatus", "GMW_TubeStatus"),
                    ("GMW_WellHeadProtector", "GMW_WellHeadProtector"),
                    ("GAR", "GAR"),
                    ("GLD_StartRegistration", "GLD_StartRegistration"),
                    ("GLD_Addition", "GLD_Addition"),
                    ("GLD_Closure", "GLD_Closure"),
                    ("FRD_StartRegistration", "FRD_StartRegistration"),
                    (
                        "FRD_GEM_MeasurementConfiguration",
                        "FRD_GEM_MeasurementConfiguration",
                    ),
                    ("FRD_GEM_Measurement", "FRD_GEM_Measurements"),
                    (
                        "FRD_EMM_InstrumentConfiguration",
                        "FRD_EMM_InstrumentConfiguration",
                    ),
                    ("FRD_EMM_Measurement", "FRD_EMM_Measurement"),
                    ("FRD_Closure", "FRD_Closure"),
                    ("CPT", "CPT"),
                    ("BHR-P", "BHR-P"),
                    ("BHR-G", "BHR-G"),
                    ("BHR-GT", "BHR-GT"),
                    ("SFR", "SFR"),
                    ("GUF_StartRegistration", "GUF_StartRegistration"),
                    ("GUF_NewLicense", "GUF_NewLicense"),
                    (
                        "GUF_ExpandedRealisedInstallation",
                        "GUF_ExpandedRealisedInstallation",
                    ),
                    (
                        "GUF_GeometryRealisedSurfaceInfiltration",
                        "GUF_GeometryRealisedSurfaceInfiltration",
                    ),
                    ("GUF_WellFunction", "GUF_WellFunction"),
                    ("GUF_Height", "GUF_Height"),
                    ("GUF_Closure", "GUF_Closure"),
                    ("GUF_AddRealisedInstallation", "GUF_AddRealisedInstallation"),
                    ("GUF_ClosureRealisedPart", "GUF_ClosureRealisedPart"),
                    ("GPD", "GPD"),
                ],
                max_length=235,
            ),
        ),
    ]
