# Generated by Django 5.2.7 on 2026-07-01 07:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0061_alter_uploadtask_registration_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectImportTask",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("bro_id", models.CharField(max_length=20)),
                (
                    "bro_domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GMN", "GMN"),
                            ("GMW", "GMW"),
                            ("GLD", "GLD"),
                            ("FRD", "FRD"),
                            ("GAR", "GAR"),
                            ("CPT", "CPT"),
                            ("BHR", "BHR"),
                            ("GUF", "GUF"),
                            ("GPD", "GPD"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "force",
                    models.BooleanField(
                        default=False,
                        help_text="When True, skip the PDOK freshness check and always re-import.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("UNFINISHED", "Unfinished"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("log", models.TextField(blank=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
            ],
        ),
    ]
