# Generated by Django 5.0.14 on 2025-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frd",
            name="internal_id",
            field=models.CharField(
                blank=True,
                help_text="Alleen beschikbaar voor de eigenaar van de put.",
                max_length=50,
                null=True,
            ),
        ),
    ]
