# Generated by Django 5.0.14 on 2025-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frd", "0002_frd_internal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="frd",
            name="linked_gmns",
            field=models.JSONField(default=list, verbose_name="Gmns"),
        ),
    ]
