# Generated by Django 5.2.7 on 2026-04-10 15:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frd", "0005_frd_monitoring_tube"),
    ]

    operations = [
        migrations.AddField(
            model_name="frd",
            name="determination_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="GeoElectricMeasurement",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("measurement_date", models.DateField(blank=True, null=True)),
                (
                    "determination_procedure",
                    models.CharField(max_length=100, null=True),
                ),
                ("evaluation_procedure", models.CharField(max_length=100, null=True)),
                (
                    "frd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_electric_measurements",
                        to="frd.frd",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Geo-electric measurements",
            },
        ),
        migrations.CreateModel(
            name="GeoElectricMeasure",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resistance", models.CharField(max_length=50, null=True)),
                (
                    "related_measurement_configuration",
                    models.CharField(max_length=50, null=True),
                ),
                (
                    "geo_electric_measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="frd.geoelectricmeasurement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Geo-electric measures",
            },
        ),
        migrations.CreateModel(
            name="CalculatedApparentFormationResistance",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("evaluation_procedure", models.CharField(max_length=100, null=True)),
                ("values", models.TextField(blank=True, null=True)),
                (
                    "geo_electric_measurement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_apparent_formation_resistance",
                        to="frd.geoelectricmeasurement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Calculated apparent formation resistances",
            },
        ),
        migrations.CreateModel(
            name="MeasurementConfiguration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("measurement_configuration_id", models.CharField(max_length=50)),
                ("measurement_pair", models.JSONField(blank=True, null=True)),
                ("current_pair", models.JSONField(blank=True, null=True)),
                (
                    "frd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_configurations",
                        to="frd.frd",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Measurement configurations",
            },
        ),
    ]
