# Generated by Django 5.2.7 on 2026-04-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_alter_uploadtask_registration_type"),
        ("frd", "0007_calculatedapparentformationresistance_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatedapparentformationresistance",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="geoelectricmeasure",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="geoelectricmeasurement",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measurementconfiguration",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
    ]
