FIELD_PARAMETER_OPTIONS = {
    "pH": {
        "parameter_id": 1398,
        "unit": "1",
    },
    "Zuurstof (mg/l)": {
        "parameter_id": 1701,
        "unit": "mg/l",
    },
    "Geleidbaarheid (mS/m)": {
        "parameter_id": 3548,
        "unit": "mS/m",
    },
    "Temperatuur (°C)": {
        "parameter_id": 1522,
        "unit": "Cel",
    },
    "Troebelheid (NTU)": {
        "parameter_id": 2031,
        "unit": "[NTU]",
    },
    "Alkaliniteit (HCO3 - mg/l)": {
        "parameter_id": 374,
        "unit": "mg/l",
    },
}

# This list was automatically created by using the 3rd tab in a lab research excel file.
# Save the aquacode, validationmethod and analyticalTechnique columns as csv.
# Use this data to create a json file with the LAB_PARAMETER_OPTIONS structure.
# Then use this json as input for a next script, where https://docs.geostandaarden.nl/bro/def-im-gar-20230607/#detail_class_Model_Parameterlijst
# is used to fill in the parameter_ids and units.
# Some parameters from the lab Excel were not found in the BRO list. These have been removed.

LAB_PARAMETER_OPTIONS = {
    "FRD-903": {
        "parameter_id": 5741,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "134DClFy3C1y": {
        "parameter_id": 2817,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "134DClFyurum": {
        "parameter_id": 2818,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "14iC3yFyurum": {
        "parameter_id": 4944,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "11DClC2a": {
        "parameter_id": 8,
        "unit": "ug/l",
        "validationMethod": "I15680.03",
        "analyticalTechnique": "GC-MS",
    },
    "t1011DHOx101": {
        "parameter_id": 5111,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "etnetDol": {
        "parameter_id": 2294,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "17bestDol": {
        "parameter_id": 2314,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "H-PFC10asfzr": {
        "parameter_id": 5830,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "H-PFC12asfzr": {
        "parameter_id": 5831,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "H-PFC6asfzr": {
        "parameter_id": 5996,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "2PFC6yC2a1sf": {
        "parameter_id": 5517,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "234TClFol": {
        "parameter_id": 83,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "235TClFol": {
        "parameter_id": 86,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "236TClFol": {
        "parameter_id": 89,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "245TClFol": {
        "parameter_id": 101,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "245T": {
        "parameter_id": 102,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "246TClFol": {
        "parameter_id": 106,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "s2425DClAn": {
        "parameter_id": 108,
        "unit": "ug/l",
        "validationMethod": "Inhouse",
        "analyticalTechnique": "GC-MS",
    },
    "24D": {
        "parameter_id": 116,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "24DDD": {
        "parameter_id": 111,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "24DDT": {
        "parameter_id": 113,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "24DClFol": {
        "parameter_id": 115,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "24DB": {
        "parameter_id": 117,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "24DC1yFol": {
        "parameter_id": 124,
        "unit": "ug/l",
        "validationMethod": "Inhouse",
        "analyticalTechnique": "GC-MS",
    },
    "24DNO2Fol": {
        "parameter_id": 669,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "26DClBenAd": {
        "parameter_id": 135,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "26xyldne": {
        "parameter_id": 2944,
        "unit": "ug/l",
        "validationMethod": "Inhouse",
        "analyticalTechnique": "GC-MS",
    },
    "2Aoactfnn": {
        "parameter_id": 2950,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "2HOxatzne": {
        "parameter_id": 2999,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DNOC": {
        "parameter_id": 668,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "2NO2Fol": {
        "parameter_id": 170,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "345TClFol": {
        "parameter_id": 177,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "44DDE": {
        "parameter_id": 216,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "42monoPAP": {
        "parameter_id": 6453,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clxlnl": {
        "parameter_id": 3486,
        "unit": "ug/l",
        "validationMethod": "D12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "4ClFol": {
        "parameter_id": 229,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "4CPA": {
        "parameter_id": 2412,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "4NO2Fol": {
        "parameter_id": 235,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "bisPFC10yPO4": {
        "parameter_id": 5998,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "abmtne": {
        "parameter_id": 2304,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "acsfmeK": {
        "parameter_id": 3131,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "actmpd": {
        "parameter_id": 3135,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "acnfn": {
        "parameter_id": 3127,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "alDcSO": {
        "parameter_id": 267,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "aedsfn": {
        "parameter_id": 269,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Al": {
        "parameter_id": 284,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "amttdn": {
        "parameter_id": 5242,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "amdTzinzr": {
        "parameter_id": 3165,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Aoprld": {
        "parameter_id": 5561,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "amsbm": {
        "parameter_id": 5137,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "amtl": {
        "parameter_id": 287,
        "unit": "ug/l",
        "validationMethod": "Inhouse",
        "analyticalTechnique": "LC-MS-MS",
    },
    "NH4": {
        "parameter_id": 289,
        "unit": "mg/l",
        "validationMethod": "I15923-1.13",
        "analyticalTechnique": "DA-S",
    },
    "AMPA": {
        "parameter_id": 292,
        "unit": "ug/l",
        "validationMethod": "I16308.17",
        "analyticalTechnique": "LC-MS-MS",
    },
    "antcnn": {
        "parameter_id": 300,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Sb": {
        "parameter_id": 301,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "As": {
        "parameter_id": 310,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "aslm": {
        "parameter_id": 323,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "atnll": {
        "parameter_id": 3186,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "atzne": {
        "parameter_id": 325,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "azsfrn": {
        "parameter_id": 5028,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C2yazfs": {
        "parameter_id": 327,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "C1yazfs": {
        "parameter_id": 328,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "aztmcne": {
        "parameter_id": 3198,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "azoxsbn": {
        "parameter_id": 3196,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Ba": {
        "parameter_id": 333,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "benlxl": {
        "parameter_id": 336,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "benDocb": {
        "parameter_id": 337,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "benfn": {
        "parameter_id": 3213,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "bentzn": {
        "parameter_id": 340,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "bentavlcbiC3": {
        "parameter_id": 3218,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Be": {
        "parameter_id": 362,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "bedsfn": {
        "parameter_id": 365,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "bezafbt": {
        "parameter_id": 2463,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "bfnx": {
        "parameter_id": 375,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "biftn": {
        "parameter_id": 376,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "bispll": {
        "parameter_id": 3266,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "bittnl": {
        "parameter_id": 3268,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "bixfn": {
        "parameter_id": 5077,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "B": {
        "parameter_id": 386,
        "unit": "ug/l",
        "validationMethod": "I11885.98",
        "analyticalTechnique": "ICP-MS",
    },
    "boscld": {
        "parameter_id": 3272,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "bromcl": {
        "parameter_id": 390,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Br": {
        "parameter_id": 391,
        "unit": "mg/l",
        "validationMethod": "I10304-1.09",
        "analyticalTechnique": "IC ",
    },
    "BrOxnl": {
        "parameter_id": 394,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "buprmt": {
        "parameter_id": 403,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Cd": {
        "parameter_id": 441,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "caffine": {
        "parameter_id": 442,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Ca": {
        "parameter_id": 447,
        "unit": "mg/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "carbmzpne": {
        "parameter_id": 3380,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "carbrl": {
        "parameter_id": 458,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "carbdzm": {
        "parameter_id": 460,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "carbtAd": {
        "parameter_id": 3384,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "carftznC2y": {
        "parameter_id": 3386,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Clafncl": {
        "parameter_id": 2497,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "chloratnlpl": {
        "parameter_id": 5175,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Clpfm": {
        "parameter_id": 492,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "C2yClprfs": {
        "parameter_id": 494,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "ClT4ccne": {
        "parameter_id": 3481,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Cltlnl": {
        "parameter_id": 497,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Cltlrn": {
        "parameter_id": 503,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Clidzn": {
        "parameter_id": 507,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Cl": {
        "parameter_id": 508,
        "unit": "mg/l",
        "validationMethod": "I15923-1.13",
        "analyticalTechnique": "DA-S",
    },
    "Cr": {
        "parameter_id": 517,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "cipfxcne": {
        "parameter_id": 3436,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clartmcne": {
        "parameter_id": 3448,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clodnfppgl": {
        "parameter_id": 3466,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clofbnzr": {
        "parameter_id": 2464,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clomzn": {
        "parameter_id": 3468,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clopdl": {
        "parameter_id": 6136,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cloprld": {
        "parameter_id": 526,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clotandne": {
        "parameter_id": 3472,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "clotmzl": {
        "parameter_id": 3473,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "crotmtn": {
        "parameter_id": 6451,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "CNazne": {
        "parameter_id": 534,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cyazfAd": {
        "parameter_id": 3528,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cycffAd": {
        "parameter_id": 2478,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cycxdm": {
        "parameter_id": 2462,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cyffAd": {
        "parameter_id": 5562,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cyftn": {
        "parameter_id": 2232,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "cypcnzl": {
        "parameter_id": 3537,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cypdnl": {
        "parameter_id": 3538,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cyrmzne": {
        "parameter_id": 3542,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "damnzde": {
        "parameter_id": 3551,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DEET": {
        "parameter_id": 2308,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "dmtn": {
        "parameter_id": 563,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "desC2yatzne": {
        "parameter_id": 571,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "desC2ytC4yaz": {
        "parameter_id": 3614,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "desiC3yatzne": {
        "parameter_id": 573,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "desmdfm": {
        "parameter_id": 3616,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "desFyClidzn": {
        "parameter_id": 3615,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "valum": {
        "parameter_id": 4913,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Daznn": {
        "parameter_id": 592,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dcba": {
        "parameter_id": 602,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dcbnl": {
        "parameter_id": 603,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "24DP": {
        "parameter_id": 140,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DClvs": {
        "parameter_id": 624,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dclofnc": {
        "parameter_id": 2466,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "dieldn": {
        "parameter_id": 633,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Dfncnzl": {
        "parameter_id": 3627,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dfbzrn": {
        "parameter_id": 648,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dffncn": {
        "parameter_id": 3624,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dikglc": {
        "parameter_id": 3644,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "dikglNa": {
        "parameter_id": 5563,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DmtCl": {
        "parameter_id": 3652,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DmtAd": {
        "parameter_id": 3651,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dmtat": {
        "parameter_id": 653,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dmtmf": {
        "parameter_id": 3654,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DMST": {
        "parameter_id": 3650,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dnsb": {
        "parameter_id": 671,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dntb": {
        "parameter_id": 672,
        "unit": "ug/l",
        "validationMethod": "D38407-35.10",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Dtann": {
        "parameter_id": 3692,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "sDtocbmt": {
        "parameter_id": 681,
        "unit": "ug/l",
        "validationMethod": "Inhouse",
        "analyticalTechnique": "GC-MS",
    },
    "Durn": {
        "parameter_id": 683,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Corg": {
        "parameter_id": 1318,
        "unit": "mg/l",
        "validationMethod": "N1484.97",
        "analyticalTechnique": "IR",
    },
    "dodmf": {
        "parameter_id": 3668,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "dodne": {
        "parameter_id": 2455,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "doxccne": {
        "parameter_id": 3672,
        "unit": "ng/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "emmtn": {
        "parameter_id": 3705,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "enrfxcne": {
        "parameter_id": 3713,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "epxcnzl": {
        "parameter_id": 3718,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "ertmcne": {
        "parameter_id": 2480,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "esfvlrt": {
        "parameter_id": 3723,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "esTol": {
        "parameter_id": 2295,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "oestn": {
        "parameter_id": 2313,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "etfmst": {
        "parameter_id": 721,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "etpfs": {
        "parameter_id": 722,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C2oxsfrn": {
        "parameter_id": 3346,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "etxzl": {
        "parameter_id": 3739,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "eTDazl": {
        "parameter_id": 740,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "fenmdn": {
        "parameter_id": 2362,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fenamfs": {
        "parameter_id": 745,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fenzn": {
        "parameter_id": 2481,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fenhxAd": {
        "parameter_id": 3764,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "feNO2ton": {
        "parameter_id": 750,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "fenfbt": {
        "parameter_id": 2482,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fenOxcb": {
        "parameter_id": 3768,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fenppmf": {
        "parameter_id": 3771,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "fenprAe": {
        "parameter_id": 5564,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fenrn": {
        "parameter_id": 2451,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fipnl": {
        "parameter_id": 3786,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "floncmd": {
        "parameter_id": 3793,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "flurslm": {
        "parameter_id": 3829,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fluaznm": {
        "parameter_id": 773,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "flubDad": {
        "parameter_id": 5174,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fludoxnl": {
        "parameter_id": 3808,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "flumoxzn": {
        "parameter_id": 3812,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fluopclde": {
        "parameter_id": 3816,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fluoprm": {
        "parameter_id": 5245,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "F": {
        "parameter_id": 1853,
        "unit": "mg/l",
        "validationMethod": "N6578.85",
        "analyticalTechnique": "POTM",
    },
    "fluoxsbn": {
        "parameter_id": 3818,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "flurOxpr": {
        "parameter_id": 2363,
        "unit": "ug/l",
        "validationMethod": "D38407-35.10",
        "analyticalTechnique": "LC-MS-MS",
    },
    "flutlnl": {
        "parameter_id": 2305,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fluxprxd": {
        "parameter_id": 5078,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "forasfrn": {
        "parameter_id": 3836,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fostazt": {
        "parameter_id": 3845,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "fursmde": {
        "parameter_id": 3854,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "gabptne": {
        "parameter_id": 3857,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "cHCH": {
        "parameter_id": 816,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "GELDHD": {
        "parameter_id": 3548,
        "unit": "mS/m",
        "validationMethod": "I7888.94",
        "analyticalTechnique": "COND",
    },
    "gemfbzl": {
        "parameter_id": 2469,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "glufsnt": {
        "parameter_id": 3877,
        "unit": "ug/l",
        "validationMethod": "I16308.17",
        "analyticalTechnique": "LC-MS-MS",
    },
    "glyfst": {
        "parameter_id": 840,
        "unit": "ug/l",
        "validationMethod": "I16308.17",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Hxznn": {
        "parameter_id": 871,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "hextazx": {
        "parameter_id": 3935,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "HCltazde": {
        "parameter_id": 3928,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "ibpfn": {
        "parameter_id": 2470,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "iffAd": {
        "parameter_id": 3984,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Fe": {
        "parameter_id": 879,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "imzll": {
        "parameter_id": 2300,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "imzmx": {
        "parameter_id": 5047,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "imdcpd": {
        "parameter_id": 2306,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "indmtcne": {
        "parameter_id": 2471,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "IsfrnC1y": {
        "parameter_id": 4027,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "johxl": {
        "parameter_id": 4040,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "jopmdl": {
        "parameter_id": 4043,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "jopmde": {
        "parameter_id": 4042,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "jotlmnzr": {
        "parameter_id": 4045,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "joxgnzr": {
        "parameter_id": 4046,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "ipDon": {
        "parameter_id": 890,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "iClidzn": {
        "parameter_id": 3981,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "iptrn": {
        "parameter_id": 913,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "isprzm": {
        "parameter_id": 5079,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "isxbn": {
        "parameter_id": 4030,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "iOaftl": {
        "parameter_id": 4010,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "jompl": {
        "parameter_id": 4041,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "K": {
        "parameter_id": 920,
        "unit": "mg/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "ketpfn": {
        "parameter_id": 2472,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Co": {
        "parameter_id": 527,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Cu": {
        "parameter_id": 971,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "kresOxmC1y": {
        "parameter_id": 4063,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Hg": {
        "parameter_id": 1097,
        "unit": "ug/l",
        "validationMethod": "I12846.12",
        "analyticalTechnique": "AAS-KD",
    },
    "lcyhltn": {
        "parameter_id": 2233,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "lencl": {
        "parameter_id": 1898,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "lidcine": {
        "parameter_id": 4093,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "linrn": {
        "parameter_id": 1114,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Li": {
        "parameter_id": 1115,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Pb": {
        "parameter_id": 1116,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "lufnrn": {
        "parameter_id": 4104,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Mg": {
        "parameter_id": 1125,
        "unit": "mg/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "malton": {
        "parameter_id": 1127,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mandppAd": {
        "parameter_id": 4117,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Mn": {
        "parameter_id": 1128,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "MCPA": {
        "parameter_id": 225,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "MCPP": {
        "parameter_id": 73,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mefpDC2y": {
        "parameter_id": 4143,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "mepqCl": {
        "parameter_id": 5248,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metocb": {
        "parameter_id": 2307,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "messfrnC1y": {
        "parameter_id": 4152,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "meston": {
        "parameter_id": 4153,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mesnl": {
        "parameter_id": 4151,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mfmzn": {
        "parameter_id": 5254,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mlxl": {
        "parameter_id": 1149,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mAh": {
        "parameter_id": 4110,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mmtn": {
        "parameter_id": 1151,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mzCl": {
        "parameter_id": 1152,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metcnzl": {
        "parameter_id": 4156,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metfmne": {
        "parameter_id": 4157,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metbtazrn": {
        "parameter_id": 1148,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metdton": {
        "parameter_id": 1155,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C1oxfnzde": {
        "parameter_id": 3318,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C1ydesFyClid": {
        "parameter_id": 3331,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metbmrn": {
        "parameter_id": 1184,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metlCl": {
        "parameter_id": 1185,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metpll": {
        "parameter_id": 2485,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metxrn": {
        "parameter_id": 1187,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metfnn": {
        "parameter_id": 4158,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "metbzn": {
        "parameter_id": 1188,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C1ymsfrn": {
        "parameter_id": 2453,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "mevfs": {
        "parameter_id": 1191,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Mo": {
        "parameter_id": 1243,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Mlnrn": {
        "parameter_id": 1253,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "monrn": {
        "parameter_id": 1254,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "DC1ysAd": {
        "parameter_id": 5565,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "nappAd": {
        "parameter_id": 4230,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "napxn": {
        "parameter_id": 2474,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Na": {
        "parameter_id": 1262,
        "unit": "mg/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "EtFOSAA": {
        "parameter_id": 5744,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "nicsfrn": {
        "parameter_id": 4254,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Ni": {
        "parameter_id": 1267,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "NO3": {
        "parameter_id": 1270,
        "unit": "mg/l",
        "validationMethod": "I15923-1.13",
        "analyticalTechnique": "DA-S",
    },
    "NO2": {
        "parameter_id": 1273,
        "unit": "mg/l",
        "validationMethod": "I15923-1.13",
        "analyticalTechnique": "DA-S",
    },
    "MeFOSA": {
        "parameter_id": 6001,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "N-MeFOSAA": {
        "parameter_id": 5937,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "norfxcne": {
        "parameter_id": 4278,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "ofxcne": {
        "parameter_id": 4310,
        "unit": "ng/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PO4": {
        "parameter_id": 1334,
        "unit": "mg/l",
        "validationMethod": "I15923-1.13",
        "analyticalTechnique": "DA-S",
    },
    "Oaml": {
        "parameter_id": 1343,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Oasfrn": {
        "parameter_id": 4301,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "oxzpm": {
        "parameter_id": 4337,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C1yOxdmtn": {
        "parameter_id": 568,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "OxT4ccnHCl": {
        "parameter_id": 5124,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pacbtzl": {
        "parameter_id": 4344,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "parctml": {
        "parameter_id": 4347,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "paroonC1y": {
        "parameter_id": 4350,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pencnzl": {
        "parameter_id": 2302,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "penccrn": {
        "parameter_id": 2301,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pendmtln": {
        "parameter_id": 1971,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "PeClFol": {
        "parameter_id": 1390,
        "unit": "ug/l",
        "validationMethod": "N12673.99",
        "analyticalTechnique": "GC-MS",
    },
    "L_PFBS": {
        "parameter_id": 3895,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFBA": {
        "parameter_id": 4437,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "L_PFDS": {
        "parameter_id": 3898,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFDA": {
        "parameter_id": 4438,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFDPA": {
        "parameter_id": 6455,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFDoA": {
        "parameter_id": 4439,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "42FTOH": {
        "parameter_id": 6452,
        "unit": "ug/l",
        "validationMethod": "Inhouse",
        "analyticalTechnique": "GC-MS",
    },
    "L_PFHpS": {
        "parameter_id": 3931,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFHpA": {
        "parameter_id": 4440,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "L_PFHxS": {
        "parameter_id": 3932,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFHxA": {
        "parameter_id": 4441,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFC16azr": {
        "parameter_id": 5735,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFNA": {
        "parameter_id": 4442,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFOSA": {
        "parameter_id": 4446,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFOS": {
        "parameter_id": 4445,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFOA": {
        "parameter_id": 4443,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFOA_NH4": {
        "parameter_id": 5970,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFC18azr": {
        "parameter_id": 5736,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFOPA": {
        "parameter_id": 6454,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFC5asfzr": {
        "parameter_id": 5935,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFPA": {
        "parameter_id": 4448,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFPeDA": {
        "parameter_id": 6456,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFTeDA": {
        "parameter_id": 4450,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFTDA": {
        "parameter_id": 4449,
        "unit": "ug/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "PFUdA": {
        "parameter_id": 4451,
        "unit": "ng/l",
        "validationMethod": "I21675.19",
        "analyticalTechnique": "LC-MS-MS",
    },
    "permtn": {
        "parameter_id": 1394,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "pH": {
        "parameter_id": 1398,
        "unit": "1",
        "validationMethod": "I10523.12",
        "analyticalTechnique": "POTM",
    },
    "fenmdfm": {
        "parameter_id": 3765,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pinadn": {
        "parameter_id": 4459,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "piprnbO": {
        "parameter_id": 1405,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pirmcb": {
        "parameter_id": 1406,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "C1yprmfs": {
        "parameter_id": 1408,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "primdn": {
        "parameter_id": 2489,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "proClaz": {
        "parameter_id": 1416,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "procmdn": {
        "parameter_id": 1417,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "propmcb": {
        "parameter_id": 1424,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "propcnzl": {
        "parameter_id": 1429,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "propxr": {
        "parameter_id": 1432,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "propnll": {
        "parameter_id": 2491,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "propfnzn": {
        "parameter_id": 4494,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "propAd": {
        "parameter_id": 1438,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "prosfcb": {
        "parameter_id": 2361,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "prosfrn": {
        "parameter_id": 4507,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "protocnzl": {
        "parameter_id": 4510,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "protocnzdto": {
        "parameter_id": 5252,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pymtzne": {
        "parameter_id": 4521,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrcsbn": {
        "parameter_id": 4524,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrffnC2y": {
        "parameter_id": 4529,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrdt": {
        "parameter_id": 4527,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrdll": {
        "parameter_id": 5249,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrmtnl": {
        "parameter_id": 2303,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrpxfn": {
        "parameter_id": 4533,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "pyrslm": {
        "parameter_id": 4535,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "quinmrc": {
        "parameter_id": 4543,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "quincmn": {
        "parameter_id": 4540,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "quizlfC2y": {
        "parameter_id": 4546,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "rimsfrn": {
        "parameter_id": 4570,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "roxtmcne": {
        "parameter_id": 2492,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Se": {
        "parameter_id": 1476,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "siltofm": {
        "parameter_id": 4654,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "simzne": {
        "parameter_id": 1480,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "endsfn": {
        "parameter_id": 2161,
        "unit": "ug/l",
        "validationMethod": "I6468.97",
        "analyticalTechnique": "AUTOMATISCH",
    },
    "sotll": {
        "parameter_id": 4675,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "spirttmt": {
        "parameter_id": 5056,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Sr": {
        "parameter_id": 1501,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "sulcton": {
        "parameter_id": 4735,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "SO4": {
        "parameter_id": 1508,
        "unit": "mg/l",
        "validationMethod": "I15923-1.13",
        "analyticalTechnique": "DA-S",
    },
    "sulfdazne": {
        "parameter_id": 4737,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "sulfdmdne": {
        "parameter_id": 2494,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "sulfmtoazl": {
        "parameter_id": 2475,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "sulfprdne": {
        "parameter_id": 4742,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "sulfsfrn": {
        "parameter_id": 5058,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "tebcnzl": {
        "parameter_id": 2298,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "tefbzrn": {
        "parameter_id": 2454,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "teftn": {
        "parameter_id": 4825,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Te": {
        "parameter_id": 1520,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "tembtone": {
        "parameter_id": 5112,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "T": {
        "parameter_id": 1522,
        "unit": "Cel",
        "validationMethod": "I10523.12",
        "analyticalTechnique": "POTM",
    },
    "terbtn": {
        "parameter_id": 1524,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "terC4yazne": {
        "parameter_id": 1525,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "T4mtn": {
        "parameter_id": 1548,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Tl": {
        "parameter_id": 1553,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "tabdzl": {
        "parameter_id": 4770,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "thiacpd": {
        "parameter_id": 4863,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "thiamtxm": {
        "parameter_id": 4864,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "thifsfrnC1y": {
        "parameter_id": 4867,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "toDcb": {
        "parameter_id": 2447,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "tofnC1y": {
        "parameter_id": 4882,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Sn": {
        "parameter_id": 1564,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Ti": {
        "parameter_id": 1565,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "tolcfsC1y": {
        "parameter_id": 1567,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "tolfande": {
        "parameter_id": 2235,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "topmzn": {
        "parameter_id": 4884,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Ptot": {
        "parameter_id": 4188,
        "unit": "mg/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "tramdl": {
        "parameter_id": 4891,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Tadmfn": {
        "parameter_id": 1586,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Tadmnl": {
        "parameter_id": 2297,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Talt": {
        "parameter_id": 4773,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "TbnrC1y": {
        "parameter_id": 4785,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "TC4yPO4": {
        "parameter_id": 1591,
        "unit": "ug/l",
        "validationMethod": "D38407-37.13",
        "analyticalTechnique": "GC-MS-MS",
    },
    "Tcpr": {
        "parameter_id": 2450,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Tfxsbn": {
        "parameter_id": 4846,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "TfsfrnC1y": {
        "parameter_id": 4844,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "Tmtpm": {
        "parameter_id": 2496,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "TnxpcC2y": {
        "parameter_id": 4878,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "tritsfrn": {
        "parameter_id": 4897,
        "unit": "ug/l",
        "validationMethod": "D38407-36.14",
        "analyticalTechnique": "LC-MS-MS",
    },
    "tylsne": {
        "parameter_id": 4902,
        "unit": "ug/l",
        "validationMethod": "I21676.22",
        "analyticalTechnique": "LC-MS-MS",
    },
    "U": {
        "parameter_id": 1637,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "V": {
        "parameter_id": 1642,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "HCO3": {
        "parameter_id": 374,
        "unit": "mg/l",
        "validationMethod": "I9963-1.96",
        "analyticalTechnique": "POTM_TITM",
    },
    "W": {
        "parameter_id": 1685,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Ag": {
        "parameter_id": 1692,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Zn": {
        "parameter_id": 1693,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
    "Zr": {
        "parameter_id": 1695,
        "unit": "ug/l",
        "validationMethod": "I17294-2.04",
        "analyticalTechnique": "ICP-MS",
    },
}
