# Generated by Django 5.0.4 on 2024-05-06 10:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0039_alter_bulkupload_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="GAR",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("bro_id", models.CharField(max_length=18)),
                (
                    "delivery_accountable_party",
                    models.CharField(max_length=8, null=True),
                ),
                ("quality_regime", models.CharField(max_length=50, null=True)),
                ("quality_control_method", models.CharField(max_length=50, null=True)),
                ("gmw_bro_id", models.CharField(max_length=50, null=True)),
                ("tube_number", models.CharField(max_length=50, null=True)),
                ("sampling_datetime", models.DateTimeField(null=True)),
                ("sampling_standard", models.CharField(max_length=50, null=True)),
                ("pump_type", models.CharField(max_length=50, null=True)),
                ("abnormality_in_cooling", models.CharField(max_length=50, null=True)),
                ("abnormality_in_device", models.CharField(max_length=50, null=True)),
                ("polluted_by_engine", models.CharField(max_length=50, null=True)),
                ("filter_aerated", models.CharField(max_length=50, null=True)),
                (
                    "groundwater_level_dropped_too_much",
                    models.CharField(max_length=50, null=True),
                ),
                ("abnormal_filter", models.CharField(max_length=50, null=True)),
                ("sample_aerated", models.CharField(max_length=50, null=True)),
                ("hose_reused", models.CharField(max_length=50, null=True)),
                (
                    "temperature_difficult_to_measure",
                    models.CharField(max_length=50, null=True),
                ),
                ("lab_analysis_date", models.DateField(blank=True, null=True)),
                ("lab_analysis_count", models.IntegerField(null=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
            ],
        ),
    ]
