# Generated by Django 5.0.4 on 2024-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gar",
            options={"verbose_name_plural": "GAR's"},
        ),
        migrations.AlterField(
            model_name="gar",
            name="lab_analysis_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
