# Generated by Django 5.0.4 on 2024-05-06 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0002_alter_gar_options_alter_gar_lab_analysis_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gar",
            name="lab_analysis_count",
        ),
    ]
