# Generated by Django 5.0.4 on 2024-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0003_remove_gar_lab_analysis_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gar",
            name="abnormal_filter",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="abnormality_in_cooling",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="abnormality_in_device",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="filter_aerated",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="gmw_bro_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="groundwater_level_dropped_too_much",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="hose_reused",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="polluted_by_engine",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="pump_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="quality_control_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="quality_regime",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="sample_aerated",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="sampling_standard",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="temperature_difficult_to_measure",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gar",
            name="tube_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
