# Generated by Django 5.2.7 on 2026-03-11 09:41

import django.db.models.deletion
from django.db import migrations, models


def populate_monitoring_tube_fk(apps, schema_editor):
    """Populate monitoring_tube FK from gmw_bro_id + tube_number"""
    GAR = apps.get_model("gar", "GAR")
    MonitoringTube = apps.get_model("gmw", "MonitoringTube")
    _ = apps.get_model("gmw", "GMW")

    # Build lookup: {(bro_id, tube_number): MonitoringTube}
    tube_lookup = {}
    for tube in MonitoringTube.objects.select_related("gmw").all():
        key = (tube.gmw.bro_id, tube.tube_number)
        tube_lookup[key] = tube

    updated = 0
    orphaned = 0

    for gar in GAR.objects.all():
        key = (gar.gmw_bro_id, gar.tube_number)
        tube = tube_lookup.get(key)

        if tube:
            gar.monitoring_tube = tube
            gar.save(update_fields=["monitoring_tube"])
            updated += 1
        else:
            orphaned += 1
            print(f"WARNING: No tube found for {gar.gmw_bro_id} tube {gar.tube_number}")

    print(
        f"Linked {updated} groundwater analysis reports to tubes, {orphaned} orphaned"
    )


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear the FK"""
    GAR = apps.get_model("gar", "GAR")
    GAR.objects.update(monitoring_tube=None)


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0004_alter_gar_abnormal_filter_and_more"),
        ("gmw", "0022_alter_gmw_internal_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gar",
            name="monitoring_tube",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groundwater_analysis_reports",
                to="gmw.monitoringtube",
            ),
        ),
        # Populate FK from existing gmw_bro_id + tube_number
        migrations.RunPython(populate_monitoring_tube_fk, reverse_populate),
    ]
