# Generated by Django 5.2.7 on 2026-04-10 15:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0005_gar_monitoring_tube"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisProcess",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("analyses_date", models.DateField(verbose_name="Datum van analyse")),
                (
                    "analytical_technique",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Analysetechniek"
                    ),
                ),
                (
                    "validation_method",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Waardebepalingsprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Laboratory processes",
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parameter",
                    models.IntegerField(max_length=100, verbose_name="Parameter ID"),
                ),
                (
                    "limit_symbol",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Limietsymbool"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=100, null=True, verbose_name="Waarde"),
                ),
                (
                    "reporting_limit",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Rapporteringsgrens"
                    ),
                ),
                (
                    "status_quality_control",
                    models.CharField(
                        choices=[
                            ("afgekeurd", "Afgekeurd"),
                            ("goedgekeurd", "Goedgekeurd"),
                            ("onbeslist", "Onbeslist"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Kwaliteitscontrole status",
                    ),
                ),
                (
                    "analysis_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_analyses",
                        to="gar.analysisprocess",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Laboratory analyses",
            },
        ),
        migrations.CreateModel(
            name="FieldMeasurement",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameter", models.IntegerField(verbose_name="Parameter ID")),
                (
                    "field_measurement_value",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "quality_control_status",
                    models.CharField(
                        choices=[
                            ("afgekeurd", "Afgekeurd"),
                            ("goedgekeurd", "Goedgekeurd"),
                            ("onbeslist", "Onbeslist"),
                            ("onbekend", "Onbekend"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_measurements",
                        to="gar.gar",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Field measurements",
            },
        ),
        migrations.CreateModel(
            name="LaboratoryResearch",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("laboratory_kvk_number", models.CharField(max_length=100, null=True)),
                (
                    "gar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_researches",
                        to="gar.gar",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Laboratory researches",
            },
        ),
        migrations.AddField(
            model_name="analysisprocess",
            name="laboratory_research",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratory_processes",
                to="gar.laboratoryresearch",
            ),
        ),
    ]
