# Generated by Django 5.2.7 on 2026-04-13 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0006_analysisprocess_analysis_fieldmeasurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmeasurement",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldmeasurement",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="laboratoryresearch",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laboratoryresearch",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="parameter",
            field=models.IntegerField(verbose_name="Parameter ID"),
        ),
    ]
