# Generated by Django 5.2.7 on 2026-04-13 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0007_fieldmeasurement_created_fieldmeasurement_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysis",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="analysisprocess",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysisprocess",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
