# Generated by Django 5.2.7 on 2026-04-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_alter_uploadtask_registration_type"),
        ("gar", "0008_analysis_created_analysis_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysisprocess",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldmeasurement",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laboratoryresearch",
            name="data_owner",
            field=models.ForeignKey(
                default="f77902a2-57be-477c-90ab-153e0d175726",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organisation",
            ),
            preserve_default=False,
        ),
    ]
