# Generated by Django 5.2.7 on 2026-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0009_analysis_data_owner_analysisprocess_data_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="unit",
            field=models.CharField(max_length=100, null=True, verbose_name="Eenheid"),
        ),
        migrations.AddField(
            model_name="fieldmeasurement",
            name="unit",
            field=models.CharField(max_length=100, null=True, verbose_name="Eenheid"),
        ),
        migrations.AlterField(
            model_name="fieldmeasurement",
            name="field_measurement_value",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Waarde veldmeting"
            ),
        ),
        migrations.AlterField(
            model_name="fieldmeasurement",
            name="quality_control_status",
            field=models.CharField(
                choices=[
                    ("afgekeurd", "Afgekeurd"),
                    ("goedgekeurd", "Goedgekeurd"),
                    ("onbeslist", "Onbeslist"),
                    ("onbekend", "Onbekend"),
                ],
                max_length=100,
                null=True,
                verbose_name="Kwaliteitscontrole status",
            ),
        ),
    ]
