# Generated by Django 5.2.7 on 2026-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0010_analysis_unit_fieldmeasurement_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gar",
            name="colour_strength",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gar",
            name="primary_colour",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gar",
            name="secondary_colour",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
