# Generated by Django 5.0.4 on 2024-12-10 07:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_alter_uploadtask_registration_type"),
        ("gld", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementTvp",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("time", models.CharField(max_length=100)),
                ("value", models.FloatField(blank=True, null=True)),
                ("status_quality_control", models.CharField(max_length=100, null=True)),
                (
                    "censoring_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "censoring_limit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Measurement time-value pairs",
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("observation_id", models.CharField(max_length=100)),
                ("begin_position", models.CharField(max_length=100, null=True)),
                ("end_position", models.CharField(max_length=100, null=True)),
                ("result_time", models.CharField(max_length=100, null=True)),
                ("validation_status", models.CharField(max_length=100, null=True)),
                ("investigator_kvk", models.CharField(max_length=100, null=True)),
                ("observation_type", models.CharField(max_length=100, null=True)),
                ("process_reference", models.CharField(max_length=100, null=True)),
                (
                    "air_pressure_compensation_type",
                    models.CharField(max_length=100, null=True),
                ),
                ("evaluation_procedure", models.CharField(max_length=100, null=True)),
                (
                    "measurement_instrument_type",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Observations",
            },
        ),
    ]
