# Generated by Django 5.0.4 on 2025-01-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gld", "0002_measurementtvp_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="gld",
            name="nr_of_observations",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="measurementtvp",
            name="observation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gld.observation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="observation",
            name="gld",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="gld.gld"
            ),
            preserve_default=False,
        ),
    ]
