# Generated by Django 5.0.4 on 2025-01-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gld", "0003_gld_nr_of_observations_measurementtvp_observation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gld",
            name="nr_of_observations",
        ),
        migrations.AddField(
            model_name="gld",
            name="linked_gmns",
            field=models.JSONField(default=list, verbose_name="Gmns"),
        ),
        migrations.AlterField(
            model_name="measurementtvp",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="gld.observation",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="gld",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="gld.gld",
            ),
        ),
    ]
