# Generated by Django 5.0.4 on 2025-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gld", "0004_remove_gld_nr_of_observations_gld_linked_gmns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="begin_position",
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name="observation",
            name="end_position",
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name="observation",
            name="result_time",
            field=models.DateTimeField(max_length=100),
        ),
    ]
