# Generated by Django 5.2.7 on 2025-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gld", "0006_gld_internal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gld",
            name="internal_id",
            field=models.CharField(
                blank=True,
                help_text="Alleen beschikbaar voor de eigenaar van de put.",
                max_length=100,
                null=True,
            ),
        ),
    ]
