# Generated by Django 5.0.1 on 2024-02-05 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GMN",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bro_id", models.CharField(max_length=18)),
            ],
            options={
                "verbose_name_plural": "GMN's",
            },
        ),
    ]
