# Generated by Django 5.0.1 on 2024-02-06 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measuringpoint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measuring_point_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("measuringpoint_start_date", models.DateField(blank=True, null=True)),
                ("tube_gml_id", models.CharField(blank=True, max_length=50, null=True)),
                ("gmw_bro_id", models.CharField(blank=True, max_length=50, null=True)),
                ("tube_number", models.CharField(blank=True, max_length=50, null=True)),
                ("tube_start_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="gmn",
            name="delivery_accountable_party",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="delivery_context",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="groundwater_aspect",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="monitoring_purpose",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="object_registration_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="quality_regime",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="registration_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gmn",
            name="start_date_monitoring",
            field=models.DateField(blank=True, null=True),
        ),
    ]
