# Generated by Django 5.0.1 on 2024-02-06 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0002_measuringpoint_gmn_delivery_accountable_party_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measuringpoint",
            old_name="measuring_point_code",
            new_name="measuringpoint_code",
        ),
    ]
