# Generated by Django 5.0.1 on 2024-02-06 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0005_measuringpoint_gmn"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmn",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gmn",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="measuringpoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measuringpoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
