# Generated by Django 5.0.1 on 2024-02-13 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0006_gmn_created_at_gmn_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GMNStartregistration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("register", "register"),
                            ("replace", "replace"),
                            ("move", "move"),
                        ],
                        max_length=235,
                    ),
                ),
                ("request_reference", models.CharField(max_length=150)),
                ("delivery_accountable_party", models.CharField(max_length=150)),
                (
                    "quality_regime",
                    models.CharField(
                        choices=[("IMBRO", "IMBRO"), ("IMBRO/A", "IMBRO/A")],
                        max_length=235,
                    ),
                ),
                ("object_id_accountable_party", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                (
                    "delivery_context",
                    models.CharField(
                        choices=[
                            (
                                "waterwetStrategischGrondwaterbeheer",
                                "waterwetStrategischGrondwaterbeheer",
                            ),
                            (
                                "waterwetGrondwaterzorgplicht",
                                "waterwetGrondwaterzorgplicht",
                            ),
                            (
                                "waterwetOnttrekkingInfiltratie",
                                "waterwetOnttrekkingInfiltratie",
                            ),
                            ("waterwetPeilbeheer", "waterwetPeilbeheer"),
                            (
                                "waterwetWaterstaatswerkAanlegWijziging",
                                "waterwetWaterstaatswerkAanlegWijziging",
                            ),
                            (
                                "waterwetWaterstaatswerkIngreep",
                                "waterwetWaterstaatswerkIngreep",
                            ),
                            (
                                "waterwetWaterstaatswerkBeheer",
                                "waterwetWaterstaatswerkBeheer",
                            ),
                            ("kaderrichtlijnWater", "kaderrichtlijnWater"),
                            ("waterschapswet", "waterschapswet"),
                            ("drinkwaterwet", "drinkwaterwet"),
                            ("ontgrondingenwet", "ontgrondingenwet"),
                            ("wetNatuurbescherming", "wetNatuurbescherming"),
                        ],
                        max_length=235,
                    ),
                ),
                (
                    "monitoring_purpose",
                    models.CharField(
                        choices=[
                            (
                                "strategischBeheerKwaliteitLandelijk",
                                "strategischBeheerKwaliteitLandelijk",
                            ),
                            (
                                "strategischBeheerKwantiteitLandelijk",
                                "strategischBeheerKwantiteitLandelijk",
                            ),
                            (
                                "strategischBeheerKwaliteitRegionaal",
                                "strategischBeheerKwaliteitRegionaal",
                            ),
                            (
                                "strategischBeheerKwantiteitRegionaal",
                                "strategischBeheerKwantiteitRegionaal",
                            ),
                            ("beheersingStedelijkGebied", "beheersingStedelijkGebied"),
                            (
                                "gevolgenOnttrekkingKwaliteit",
                                "gevolgenOnttrekkingKwaliteit",
                            ),
                            (
                                "gevolgenOnttrekkingKwantiteit",
                                "gevolgenOnttrekkingKwantiteit",
                            ),
                            ("gevolgenPeilbeheer", "gevolgenPeilbeheer"),
                            (
                                "gevolgenWaterstaatswerkKwaliteit",
                                "gevolgenWaterstaatswerkKwaliteit",
                            ),
                            (
                                "gevolgenWaterstaatswerkKwantiteit",
                                "gevolgenWaterstaatswerkKwantiteit",
                            ),
                            (
                                "waterstaatswerkBeheerKwaliteit",
                                "waterstaatswerkBeheerKwaliteit",
                            ),
                            (
                                "waterstaatswerkBeheerKwantiteit",
                                "waterstaatswerkBeheerKwantiteit",
                            ),
                            (
                                "veiligstellingGrondwaterKwaliteit",
                                "veiligstellingGrondwaterKwaliteit",
                            ),
                            (
                                "veiligstellingGrondwaterKwantiteit",
                                "veiligstellingGrondwaterKwantiteit",
                            ),
                            (
                                "waterstaatkundigeVerzorgingKwaliteit",
                                "waterstaatkundigeVerzorgingKwaliteit",
                            ),
                            (
                                "waterstaatkundigeVerzorgingKwantiteit",
                                "waterstaatkundigeVerzorgingKwantiteit",
                            ),
                            (
                                "veiligstellingDrinkwatervoorzieningKwaliteit",
                                "veiligstellingDrinkwatervoorzieningKwaliteit",
                            ),
                            (
                                "veiligstellingDrinkwatervoorzieningKwantiteit",
                                "veiligstellingDrinkwatervoorzieningKwantiteit",
                            ),
                            ("gevolgenOntgronding", "gevolgenOntgronding"),
                            ("natuurbescherming", "natuurbescherming"),
                            ("natuurbeheer", "natuurbeheer"),
                        ],
                        max_length=235,
                    ),
                ),
                (
                    "groundwater_aspect",
                    models.CharField(
                        choices=[
                            ("kwaliteit", "kwaliteit"),
                            ("kwantiteit", "kwantiteit"),
                        ],
                        max_length=235,
                    ),
                ),
                ("start_date_monitoring", models.DateField(null=True)),
            ],
        ),
    ]
