# Generated by Django 5.0.1 on 2024-02-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmn", "0007_gmnstartregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmnstartregistration",
            name="measuringpoints",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gmn.measuringpoint",
            ),
        ),
    ]
