# Generated by Django 5.0.1 on 2024-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmn", "0008_gmnstartregistration_measuringpoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmnstartregistration",
            name="status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
