# Generated by Django 5.0.1 on 2024-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0009_gmnstartregistration_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gmnstartregistration",
            name="measuringpoints",
        ),
        migrations.AddField(
            model_name="gmnstartregistration",
            name="measuringpoints",
            field=models.ManyToManyField(to="gmn.measuringpoint"),
        ),
    ]
