# Generated by Django 5.0.1 on 2024-02-14 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0010_remove_gmnstartregistration_measuringpoints_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GMNStartregistration",
        ),
    ]
