# Generated by Django 5.0.1 on 2024-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0014_alter_gmn_data_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmn",
            name="delivery_accountable_party",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="delivery_context",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="groundwater_aspect",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="monitoring_purpose",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="object_registration_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="quality_regime",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="registration_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="start_date_monitoring",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="gmw_bro_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="measuringpoint_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="measuringpoint_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="tube_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="tube_start_date",
            field=models.DateField(null=True),
        ),
    ]
