# Generated by Django 5.0.1 on 2024-04-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0015_alter_gmn_delivery_accountable_party_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmn",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
