# Generated by Django 5.0.4 on 2025-01-23 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0018_rename_created_at_gmn_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measuringpoint",
            options={"verbose_name_plural": "Measuring Points"},
        ),
    ]
