# Generated by Django 5.0.4 on 2025-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0019_alter_measuringpoint_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuringpoint",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("GMN_MeasuringPoint", "GMN_MeasuringPoint"),
                    ("GMN_TubeReference", "GMN_TubeReference"),
                    ("GMN_MeasuringPointEndDate", "GMN_MeasuringPointEndDate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="measuringpoint",
            name="measuringpoint_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="measuringpoint",
            name="tube_end_date",
            field=models.DateField(null=True),
        ),
    ]
