# Generated by Django 5.0.4 on 2025-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0020_measuringpoint_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuringpoint",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("GMN_MeasuringPoint", "GMN_MeasuringPoint"),
                    ("GMN_TubeReference", "GMN_TubeReference"),
                    ("GMN_MeasuringPointEndDate", "GMN_MeasuringPointEndDate"),
                    ("GMN_StartRegistration", "GMN_StartRegistration"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
