# Generated by Django 5.0.4 on 2025-03-23 16:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_bulkupload_request_type"),
        ("gmn", "0021_alter_measuringpoint_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntermediateEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GMN_MeasuringPoint", "GMN_MeasuringPoint"),
                            ("GMN_TubeReference", "GMN_TubeReference"),
                            ("GMN_MeasuringPointEndDate", "GMN_MeasuringPointEndDate"),
                            ("GMN_StartRegistration", "GMN_StartRegistration"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("event_date", models.DateField()),
                ("measuringpoint_code", models.CharField(max_length=254)),
                ("gmw_bro_id", models.CharField(max_length=30)),
                ("tube_number", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "data_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organisation",
                    ),
                ),
                (
                    "gmn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gmn.gmn"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Intermediate Events",
            },
        ),
    ]
