# Generated by Django 5.0.14 on 2025-06-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0022_intermediateevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuringpoint",
            name="gmn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measuring_points",
                to="gmn.gmn",
            ),
        ),
    ]
