# Generated by Django 5.2.7 on 2025-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0024_gmn_internal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmn",
            name="internal_id",
            field=models.CharField(
                blank=True,
                help_text="Alleen beschikbaar voor de eigenaar van de put.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gmn",
            name="quality_regime",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="gmw_bro_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="measuringpoint_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="measuringpoint",
            name="tube_number",
            field=models.CharField(max_length=50),
        ),
    ]
