# Generated by Django 5.2.7 on 2026-02-25 19:16

import django.db.models.deletion
from django.db import migrations, models


def populate_monitoring_tube_fk(apps, schema_editor):
    """Populate monitoring_tube FK from gmw_bro_id + tube_number"""
    Measuringpoint = apps.get_model("gmn", "Measuringpoint")
    MonitoringTube = apps.get_model("gmw", "MonitoringTube")
    _ = apps.get_model("gmw", "GMW")

    # Build lookup: {(bro_id, tube_number): MonitoringTube}
    tube_lookup = {}
    for tube in MonitoringTube.objects.select_related("gmw").all():
        key = (tube.gmw.bro_id, tube.tube_number)
        tube_lookup[key] = tube

    updated = 0
    orphaned = 0

    for mp in Measuringpoint.objects.all():
        key = (mp.gmw_bro_id, mp.tube_number)
        tube = tube_lookup.get(key)

        if tube:
            mp.monitoring_tube = tube
            mp.save(update_fields=["monitoring_tube"])
            updated += 1
        else:
            orphaned += 1
            print(f"WARNING: No tube found for {mp.gmw_bro_id} tube {mp.tube_number}")

    print(f"Linked {updated} measuringpoints to tubes, {orphaned} orphaned")


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear the FK"""
    Measuringpoint = apps.get_model("gmn", "Measuringpoint")
    Measuringpoint.objects.update(monitoring_tube=None)


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0025_alter_gmn_internal_id_alter_gmn_quality_regime_and_more"),
        ("gmw", "0022_alter_gmw_internal_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuringpoint",
            name="monitoring_tube",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measuring_points",
                to="gmw.monitoringtube",
            ),
        ),
        # Populate FK from existing gmw_bro_id + tube_number
        migrations.RunPython(populate_monitoring_tube_fk, reverse_populate),
    ]
