# Generated by Django 5.2.7 on 2026-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmn", "0026_measuringpoint_monitoring_tube"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmn",
            name="end_date_monitoring",
            field=models.DateField(null=True),
        ),
    ]
